/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Logica.ContenedorEstrategia;
import Logica.Estrategia;
import Logica.Horario;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author David-PC
 */
public class EstrategiasGUI extends javax.swing.JPanel {

    PrincipalGUI principal;
    ContenedorEstrategia contenedorEstrategia;
    
    public EstrategiasGUI(PrincipalGUI p) {
        p = principal;
        initComponents();
        
        contenedorEstrategia =new ContenedorEstrategia();
    }

    public ContenedorEstrategia getContenedorEstrategia() {
        return contenedorEstrategia;
    }
    
    public PrincipalGUI getPrincipal() {
        return principal;
    }
    public void cargarTabla(){
        
        //borra toda la tabla primero
        for(int i=0;i<((DefaultTableModel)estrategyT.getModel()).getRowCount();){
            ((DefaultTableModel)estrategyT.getModel()).removeRow(i);
        }
        
        //agrega lo que haya en el arraylist
        for(int i=0;i<contenedorEstrategia.getEstrategias().size();i++){
            Estrategia c = contenedorEstrategia.getEstrategias().get(i);
            String file = c.getFile();
            String name = c.getNombre();
            String status = c.isEstatus()?"Active":"Inactive";
            boolean fullBackup = c.isFullBackup();
            boolean archive = c.isArchive();
            ArrayList<String> ts = c.getTablespaces();
            ArrayList<Horario> hs = c.getHorarios();
            ((DefaultTableModel)estrategyT.getModel()).addRow(new Object[]{});
        }        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        estrategyT = new javax.swing.JTable();
        newBoton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        jLabel1.setText("Strategies");

        estrategyT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Strategy", "RMAN File", "Tablespaces", "Schedule", "Status", "Used"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(estrategyT);
        estrategyT.getColumnModel().getColumn(0).setPreferredWidth(150);
        estrategyT.getColumnModel().getColumn(1).setPreferredWidth(150);
        estrategyT.getColumnModel().getColumn(2).setPreferredWidth(150);
        estrategyT.getColumnModel().getColumn(3).setPreferredWidth(150);
        estrategyT.getColumnModel().getColumn(4).setPreferredWidth(50);
        estrategyT.getColumnModel().getColumn(5).setPreferredWidth(20);

        newBoton.setText("New");
        newBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newBotonActionPerformed(evt);
            }
        });

        jButton2.setText("Edit");

        jButton3.setText("Delete");

        jButton4.setText("Change Status");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 918, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(newBoton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton4)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newBoton)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addContainerGap(29, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void newBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newBotonActionPerformed
        CrearEditarEstrategiaGUI es = new CrearEditarEstrategiaGUI(this);
        es.setVisible(true);
    }//GEN-LAST:event_newBotonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable estrategyT;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton newBoton;
    // End of variables declaration//GEN-END:variables
}
